# Alembic configuration file

[alembic]
# path to migration scripts
script_location = app/database/migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
# file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d-%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepended_sys_path = .

# timezone to use when rendering the date
# within the "create date" string and datetime() comparisons
# string value is passed to os.environ['TZ']
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field
# set to 40 to truncate to 40 characters
# set to -1 to disable truncating
truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# logging configuration
# when set to 'false', logging is disabled in the
# alembic.env module and migration scripts.
# set to 'true' to enable logging
# sqlalchemy.url is the database connection string
# sqlalchemy.echo controls SQLAlchemy echo setting
# when 'true', it will log all SQL statements issued
sqlalchemy.url =

[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
